### ISSUE TITLE
Any copyright/license terms?

### ISSUE THREAD

**Issue by ChadAMiller** [TStand90/roguelike-tutorials-website#10]
I've been working through this tutorial for the reddit event and I just realized that I can't find any kind of copyright notice on this or the original tutorial. My own repo currently lists itself as MIT licensed (and I will keep it that way for my own additions) but I actually don't have the standing to say the same for any code taken from the tutorial. Does this or the original tutorial have any kind of copyright notice anywhere?

I imagine you and the original authors would approve of what I'm doing, but I would like to be sure if at all possible.

**Comment by HexDecimal** [comment]
The v2 tutorial is [now licensed under CC0](https://github.com/TStand90/tcod_tutorial_v2/blob/master/LICENSE.txt).

(Sorry for taking this long.)
