### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ghost** [TStand90/roguelike-tutorials-website#24]
What is the code shown in this tutorial licensed under? Is it public domain or does it have a license?

**Comment by HexDecimal** [comment]
I wouldn't mind putting the new tutorial under a permissive license such as MIT or a public domain license such as Unlicense or CC0.  I guess it depends on what @TStand90 wants.

**Comment by ghost** [comment]
The original code is under public domain, [link](http://www.roguebasin.com/index.php?title=Talk:Complete_Roguelike_Tutorial,_using_python%2Blibtcod#Copyright.2FCopyleft) so it would depend entirely on @TStand90 .

**Comment by HexDecimal** [comment]
IANAL, but "public domain" itself isn't a license, and licenses which release to the public domain are not copyleft by definition so those permissions are not passed on to derivatives unless the license stays intact.

Just saying that something is in the public domain leaves gaps in many jurisdictions, so you need to add a license such is CC0 or Unlicense to cover those gaps.  Any method not involving a license is problematic.

The nature of the tutorial implies that you are free to use the code as you wish, but if you wanted to be pedantic then there's nothing written down giving any permission to use any of the code.  All of this code is technically "all rights reserved" until this is resolved.

I plan on adding a license.  I'd go with MIT if @TStand90 wanted attribution or CC0 if not.

**Comment by TStand90** [comment]
CC0 is fine, I personally don't care about attribution. If you want attribution, @HexDecimal, then MIT is fine (you deserve credit as well).

**Comment by HexDecimal** [comment]
Then that settles it.  We'll apply a CC0 license to the tutorial:  https://choosealicense.com/licenses/cc0-1.0/
