### ISSUE TITLE
Part 1 & 2 Drawing Console Examples

### ISSUE THREAD

**Issue by andrewjcl** [TStand90/roguelike-tutorials-website#7]
The first example code in Part 2 incorrectly lists some lines as present.

Part 1 example shows the lines for drawing to '0' (default console), being removed.
![Part_01_](https://user-images.githubusercontent.com/30279619/60631700-1479c480-9e44-11e9-8f3e-34fc2c09a540.png)

Part 2 example shows deleted lines in its example
![Part_02_A](https://user-images.githubusercontent.com/30279619/60631717-29565800-9e44-11e9-8e2c-c225d3e05ea1.png)

Part 2 B example shows that those lines shouldn't exist
![Part_02_B](https://user-images.githubusercontent.com/30279619/60631733-3a06ce00-9e44-11e9-8a25-eb9c47d7d858.png)

**Comment by andrewjcl** [comment]
Also another issue, although I don't know if it qualifies as an issue so I'll just chuck it in a comment here, is that

libtcod.console_blit(con, 0, 0, screen_width, screen_height, 0, 0, 0)

is never explained, it's just added (last part of Part 1).

**Comment by HexDecimal** [comment]
#5 fixed the duplicate code removals.

`libtcod.console_blit(con, 0, 0, screen_width, screen_height, 0, 0, 0)` blits `con` to the root console so that `libtcod.console_flush()` will show what was drawn on `con`.  I've added a note about this.
